version: "3.9"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - demo-bridge
    volumes:
      - demo-volume:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skill
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  springio-api: 
    depends_on:
      - mysql
    image: springio-api:1.1.1
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: springio-api
    networks:
      - demo-bridge
    volumes:
      - /var/lib/mysql
    ports:
      - 8081:8080
    restart: always
networks:
  demo-bridge:
volumes:
  demo-volume: